<a href="https://colab.research.google.com/github/Pyro-Warrior-1884/NNDL_Assignment/blob/main/CB.EN.U4CSE22404.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
#creating a scalar tensor
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix
matrix=tf.constant([[1,2],[2,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 2, 10]], dtype=int32)>

In [ ]:
matrix.ndim


2

In [ ]:
#create another matrix
matrix2=tf.constant([[12],[12],[12]],dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 1), dtype=float16, numpy=
array([[12.],
       [12.],
       [12.]], dtype=float16)>

In [ ]:
#3 dimensional tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#Lets create tensorflow Variables
var=tf.Variable([4,4])
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 4], dtype=int32)>

Variable: The name of the variable. If you don't explicitly give it a name, TensorFlow auto-generates one.

0: Refers to the first output tensor of that variable (most variables only have one output, so it’s usually :0).

In [ ]:
#reassigning the tensor variable using (.assign)
var[0].assign(9)
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 4], dtype=int32)>

In [ ]:
var[0]=8

TypeError: 'ResourceVariable' object does not support item assignment

Assignment using direct indexing doensn't work we will have to use the (.assign()) function to reassign any values

**Note:**
We will rarely be deciding whether to use tf.constant or tf.variable,Tensorflow does this for us.However,if in doubt use tf.constant and can be changed later




---



## Creating Random Tensors


Random tensors are tensors of arbitrary size filled with random numbers



---
Creating a random constant tensor



In [ ]:
random_tensor=tf.random.uniform(shape=[] ,minval=5, maxval=10)
random_tensor


<tf.Tensor: shape=(), dtype=float32, numpy=9.98869800567627>

We are using a uniform distribution

minval: lower bound (inclusive)

maxval: upper bound (exclusive)

In [ ]:
random_vector=tf.random.uniform(shape=[2,2],dtype=tf.float16)
random_vector

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[0.1416, 0.4697],
       [0.503 , 0.2012]], dtype=float16)>


set_seed() function is used to reproduce the same sequence of numbers while generating random values

In [ ]:
tf.random.set_seed(5)
vector=tf.random.normal(shape=[2,2])
vector

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.18030666, -0.95028627],
       [-0.03964049, -0.7425406 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(5)
vector=tf.random.normal(shape=[2,2])
vector

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.18030666, -0.95028627],
       [-0.03964049, -0.7425406 ]], dtype=float32)>

In [ ]:
vector=tf.random.normal(shape=[2,2])
vector

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.22652864, 0.8106553 ],
       [0.7466094 , 0.7749703 ]], dtype=float32)>

In [ ]:
g=tf.random.Generator.from_seed(5)
gen1=g.uniform(shape=[2,2])
saved_state = g.state.read_value()
gen2=g.uniform(shape=[2,2])
print(gen1)
print(gen2)
g.reset(saved_state)
gen3=g.uniform(shape=[2,2])
print(gen3)

tf.Tensor(
[[0.567016   0.2077086 ]
 [0.18223882 0.99883735]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.0657748  0.8750659 ]
 [0.60925746 0.4647795 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.0657748  0.8750659 ]
 [0.60925746 0.4647795 ]], shape=(2, 2), dtype=float32)


we get different values in gen1 and gen2 becasue the state has advanced

gen3 and gen2 have the same values because they are created from the same state



---

## Shuffling order of elements in a  Tensors
useful when we want to changed the order of data so that it doesn not affect learning


In [ ]:
shuffle = tf.constant([[1,2],[2,3],[3,4]])
shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

In [ ]:
shuffle.ndim

2

In [ ]:
tf.random.shuffle(shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

In [ ]:
tf.random.shuffle(shuffle[0])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 1], dtype=int32)>

Seed is used to ensure we get the same random shuffling


In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(shuffle,seed=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [2, 3]], dtype=int32)>

We shoud set a global seed otherwise the operation level seed might produce non deteministics results.



---

## Some Other ways to create Tensors

In [ ]:
tf.ones(shape=[4,5])

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([2,4])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turning Numpy Arrays into tensors
The difference betweeen numpy arrays and tensors is that tensors can be run on GPU(much faster)

In [ ]:
import numpy as np

numpy_A=np.array([[1,2,3,4],[1,2,3,4]])

# X=tf.constant(matrix)  Uppercase for matrix representation and tensors
# y-tf.constant(vector) lowercase for vector representation
numpy_A.shape


(2, 4)

In [ ]:
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[1, 2, 3, 4],
       [1, 2, 3, 4]])>

we can change the shape of the tensor ensuring that the shape of tensor has the same number of elements in the numpy array

In [ ]:
B=tf.constant(numpy_A, shape=[4,2])
B

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])>

The below code creates a Tensor G using the data from  tensor T

In [ ]:
T=tf.constant([1,2,3,4])
G=tf.constant(T,shape=[2,2])
G

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

The below code uses the reshape function,it does not create a new tensor rather it gives a different view of the existing tensor

Note:We need an existing tensor to do this

In [ ]:
G=tf.reshape(T,[2,2])
G

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

##Getting Information from Tensors
Attributes:


*   Shape
*   Rank
*   Axis or dimension
*   Size



In [ ]:
#creating a rank 5 tensor
rnk_5=tf.zeros([2,2,2,2,2])
rnk_5.ndim

5

In [ ]:
rnk_5.shape

TensorShape([2, 2, 2, 2, 2])

In [ ]:
tf.size(rnk_5)

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [ ]:
print("Datatype of each element in the tensor",rnk_5.dtype)
print("Number of dimensions in the tensor",rnk_5.ndim)
print("Shape of the tensor:",rnk_5.shape)
print("Number of elements along 1st axis",rnk_5.shape[0])
print("Number of elements along last axis",rnk_5[-1].shape[-1])
print("Number of elements in the tensor:",tf.size(rnk_5).numpy())

Datatype of each element in the tensor <dtype: 'float32'>
Number of dimensions in the tensor 5
Shape of the tensor: (2, 2, 2, 2, 2)
Number of elements along 1st axis 2
Number of elements along last axis 2
Number of elements in the tensor: 32


## Indexing Tensors
Tensors can be indexed just like python lists.


In [ ]:
# getting the first 2 elements of each dimension
A=tf.constant([[[1,2],[3,5]],[[2,1],[3,4]]])
A

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 5]],

       [[2, 1],
        [3, 4]]], dtype=int32)>

In [ ]:
A[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1), dtype=int32, numpy=array([[[1]]], dtype=int32)>

In [ ]:
B=tf.zeros([4,4,4,4])


In [ ]:
#get the first element from all the dimensions except the last dimension
B[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#create a rank 2 tensor
tf.random.set_seed(42)
rnk_2=tf.random.uniform(shape=[5,5],minval=1, maxval=3,dtype=tf.int32)
rnk_2

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[2, 2, 2, 1, 1],
       [1, 2, 2, 2, 2],
       [1, 1, 2, 2, 1],
       [1, 2, 1, 2, 2],
       [2, 1, 2, 1, 2]], dtype=int32)>

In [ ]:
#get the last element of each row
rnk_2[:,-1]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 1, 2, 2], dtype=int32)>

In [ ]:
#make it into a 3dim tensor
rnk_3=tf.reshape(rnk_2,[1,5,5])
rnk_3

<tf.Tensor: shape=(1, 5, 5), dtype=int32, numpy=
array([[[2, 2, 2, 1, 1],
        [1, 2, 2, 2, 2],
        [1, 1, 2, 2, 1],
        [1, 2, 1, 2, 2],
        [2, 1, 2, 1, 2]]], dtype=int32)>

In [ ]:
#added a new dimension
X=tf.ones([4,4,4,4])
X.ndim


4

(...) is known as the ellipse operator ,it is used to represent everything inbetween,especially in larger tensor

In [ ]:
X[tf.newaxis,...]

<tf.Tensor: shape=(1, 4, 4, 4, 4), dtype=float32, numpy=
array([[[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],

In [ ]:
X[:,tf.newaxis,...]

<tf.Tensor: shape=(4, 1, 4, 4, 4), dtype=float32, numpy=
array([[[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]],



       [[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]],



       [[[[1., 1., 1., 

In [ ]:
#we can add dimensions using the tf.expand_dims() function

In [ ]:
B=tf.random.uniform([2,2])
tf.expand_dims(B,axis=0)


<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0.95831835, 0.01680839],
        [0.3156035 , 0.16013157]]], dtype=float32)>

In [ ]:
tf.expand_dims(B,axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.95831835],
        [0.01680839]],

       [[0.3156035 ],
        [0.16013157]]], dtype=float32)>