In [1]:
import torch
import torch.nn as nn
import torch.optim as optim


torch.manual_seed(42)


class Perceptron(nn.Module):
    def __init__(self):
        super(Perceptron, self).__init__()
        self.fc = nn.Linear(2, 1)  # 2 inputs → 1 output

    def forward(self, x):
        return torch.sigmoid(self.fc(x))


class XORNet(nn.Module):
    def __init__(self):
        super(XORNet, self).__init__()
        self.layer1 = nn.Linear(2, 2)
        self.layer2 = nn.Linear(2, 1)

    def forward(self, x):
        x = torch.sigmoid(self.layer1(x))
        x = torch.sigmoid(self.layer2(x))
        return x



def train_gate(model, inputs, targets, epochs=1000, lr=0.1):
    criterion = nn.BCELoss()
    optimizer = optim.SGD(model.parameters(), lr=lr)

    for epoch in range(epochs):
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()



X = torch.FloatTensor([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])


y_and = torch.FloatTensor([[0], [0], [0], [1]])
y_or  = torch.FloatTensor([[0], [1], [1], [1]])
y_xor = torch.FloatTensor([[0], [1], [1], [0]])


model_and = Perceptron()
train_gate(model_and, X, y_and, epochs=1000)
out_and = torch.round(model_and(X).detach())


model_or = Perceptron()
train_gate(model_or, X, y_or, epochs=1000)
out_or = torch.round(model_or(X).detach())


model_xor = XORNet()
train_gate(model_xor, X, y_xor, epochs=10000)
out_xor = torch.round(model_xor(X).detach())


print("=== Logic Gate Outputs ===")
print("AND Gate:")
print(out_and)

print("\nOR Gate:")
print(out_or)

print("\nXOR Gate:")
print(out_xor)


=== Logic Gate Outputs ===
AND Gate:
tensor([[0.],
        [0.],
        [0.],
        [1.]])

OR Gate:
tensor([[0.],
        [1.],
        [1.],
        [1.]])

XOR Gate:
tensor([[0.],
        [1.],
        [1.],
        [0.]])
